PKUOS - Pintos: src/tests/vm/child-linear.c File Reference
child-linear.c File Reference
#include <string.h>
#include "tests/arc4.h"
#include "tests/lib.h"
#include "tests/main.h"
Macros
#define SIZE (1024 * 1024)
Functions
int main (int argc, char *argv[])
Variables
const char * test_name = "child-linear"
Child process of page-parallel.
static char buf [SIZE]
Macro Definition Documentation
SIZE
#define SIZE (1024 * 1024)
Definition at line 12 of file child-linear.c.
Function Documentation
main()
int main (int argc , char * argv[])
Definition at line 16 of file child-linear.c.
References arc4_crypt(), arc4_init(), buf, fail(), arc4::i, SIZE, and strlen().
Variable Documentation
buf
char buf[SIZE] static
Definition at line 13 of file child-linear.c.
Referenced by main().
test_name
const char* test_name = "child-linear"
Child process of page-parallel.
Child process for syn-read test.
Encrypts 1 MB of zeros, then decrypts it, and ensures that the zeros are back.
Definition at line 10 of file child-linear.c.