PKUOS - Pintos: src/tests/filesys/base/child-syn-wrt.c File Reference
child-syn-wrt.c File Reference
#include <random.h>
#include <stdlib.h>
#include <syscall.h>
#include "tests/lib.h"
#include "tests/filesys/base/syn-write.h"
Functions
int main (int argc, char *argv[])
Variables
char buf [BUF_SIZE]
Child process for syn-read test.
Function Documentation
main()
int main (int argc , char * argv[])
Definition at line 14 of file child-syn-wrt.c.
References atoi(), buf, CHECK, CHUNK_SIZE, close(), file_name, msg(), open(), quiet, random_bytes(), random_init(), seek(), and write().
Variable Documentation
buf
char buf[BUF_SIZE]
Child process for syn-read test.
Writes into part of a test file. Other processes will be writing into other parts at the same time.
Definition at line 11 of file child-syn-wrt.c.
Referenced by main().