PKUOS - Pintos: src/examples/cmp.c File Reference
cmp.c File Reference
#include <stdio.h>
#include <syscall.h>
Functions
int main (int argc, char *argv[])
cat.c
Function Documentation
main()
int main (int argc , char * argv[])
cat.c
Compares two files.
Definition at line 9 of file cmp.c.
References buffer, EXIT_FAILURE, EXIT_SUCCESS, open(), printf(), read(), and tell().