PKUOS - Pintos: src/lib/kernel/console.h File Reference
console.h File Reference
Functions
void console_init (void)
Enable console locking.
void console_panic (void)
Notifies the console that a kernel panic is underway, which warns it to avoid trying to take the console lock from now on.
void console_print_stats (void)
lib/kernel/console.h
Function Documentation
console_init()
void console_init (void)
Enable console locking.
Definition at line 64 of file console.c.
References console_lock, lock_init(), and use_console_lock.
Referenced by pintos_init().
console_panic()
void console_panic (void)
Notifies the console that a kernel panic is underway, which warns it to avoid trying to take the console lock from now on.
Definition at line 74 of file console.c.
References use_console_lock.
Referenced by debug_panic().
console_print_stats()
void console_print_stats (void)
lib/kernel/console.h
lib/kernel/console.h
Definition at line 81 of file console.c.
References printf(), and write_cnt.
Referenced by print_stats().