PKUOS - Pintos: src/tests/userprog/create-long.c File Reference
create-long.c File Reference
#include <string.h>
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Tries to create a file with a name that is much too long, which must fail.
Function Documentation
test_main()
void test_main (void)
Tries to create a file with a name that is much too long, which must fail.
tests/main.h
Definition at line 10 of file create-long.c.
References create(), memset(), msg(), and name.