PKUOS - Pintos: src/lib/ctype.h File Reference
ctype.h File Reference
Functions
static int islower (int c)
static int isupper (int c)
static int isalpha (int c)
static int isdigit (int c)
static int isalnum (int c)
static int isxdigit (int c)
static int isspace (int c)
static int isblank (int c)
static int isgraph (int c)
static int isprint (int c)
static int iscntrl (int c)
static int isascii (int c)
static int ispunct (int c)
static int tolower (int c)
static int toupper (int c)
lib/ctype.h
Function Documentation
isalnum()
static int isalnum (int c) inline static
Definition at line 8 of file ctype.h.
References isalpha(), and isdigit().
Referenced by ispunct().
isalpha()
static int isalpha (int c) inline static
Definition at line 6 of file ctype.h.
References islower(), and isupper().
Referenced by isalnum().
isascii()
static int isascii (int c) inline static
Definition at line 20 of file ctype.h.
isblank()
static int isblank (int c) inline static
Definition at line 16 of file ctype.h.
iscntrl()
static int iscntrl (int c) inline static
Definition at line 19 of file ctype.h.
isdigit()
static int isdigit (int c) inline static
Definition at line 7 of file ctype.h.
Referenced by atoi(), expand(), isalnum(), isxdigit(), main(), and parse_conversion().
isgraph()
static int isgraph (int c) inline static
Definition at line 17 of file ctype.h.
islower()
static int islower (int c) inline static
Definition at line 4 of file ctype.h.
Referenced by isalpha(), and toupper().
isprint()
static int isprint (int c) inline static
Definition at line 18 of file ctype.h.
Referenced by hex_dump(), and ispunct().
ispunct()
static int ispunct (int c) inline static
Definition at line 21 of file ctype.h.
References isalnum(), isprint(), and isspace().
Referenced by expand().
isspace()
static int isspace (int c) inline static
Definition at line 12 of file ctype.h.
Referenced by atoi(), descramble_ata_string(), and ispunct().
isupper()
static int isupper (int c) inline static
Definition at line 5 of file ctype.h.
Referenced by isalpha(), and tolower().
isxdigit()
static int isxdigit (int c) inline static
Definition at line 9 of file ctype.h.
References isdigit().
tolower()
static int tolower (int c) inline static
Definition at line 25 of file ctype.h.
References isupper().
Referenced by keyboard_interrupt().
toupper()
static int toupper (int c) inline static
lib/ctype.h
Definition at line 26 of file ctype.h.
References islower().
Referenced by main().