PKUOS - Pintos: src/tests/filesys/extended/dir-rm-tree.c File Reference
dir-rm-tree.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include <syscall.h>
#include "tests/filesys/extended/mk-tree.h"
#include "tests/lib.h"
#include "tests/main.h"
Functions
static void remove_tree (int at, int bt, int ct, int dt)
Creates directories /0/0/0 through /3/2/2 and files in the leaf directories, then removes them.
void test_main (void)
tests/main.h
static void do_remove (const char *format,...) PRINTF_FORMAT(1
Function Documentation
do_remove()
static void do_remove (const char * format, ...) static
Definition at line 52 of file dir-rm-tree.c.
References CHECK, name, remove(), va_end, va_start, and vsnprintf().
Referenced by remove_tree().
remove_tree()
static void static void remove_tree (int at, int bt, int ct, int dt) static
Creates directories /0/0/0 through /3/2/2 and files in the leaf directories, then removes them.
Definition at line 23 of file dir-rm-tree.c.
References CHECK, do_remove(), msg(), open(), quiet, and snprintf().
Referenced by test_main().
test_main()
void test_main (void)
tests/main.h
tests/main.h
tests/main.h
This must fail, because that directory is non-empty.
tests/main.h
This must fail.
Definition at line 14 of file dir-rm-tree.c.
References make_tree(), and remove_tree().