PKUOS - Pintos: src/tests/filesys/extended/dir-vine.c File Reference
dir-vine.c File Reference
#include <string.h>
#include <stdio.h>
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Create a very deep "vine" of directories: /dir0/dir1/dir2/... and an ordinary file in each of them, until we fill up the disk.
Function Documentation
test_main()
void test_main (void)
Create a very deep "vine" of directories: /dir0/dir1/dir2/... and an ordinary file in each of them, until we fill up the disk.
tests/main.h
Then delete most of them, for two reasons. First, "tar" limits file names to 100 characters (which could be extended to 256 without much trouble). Second, a full disk has no room for the tar archive.
Definition at line 17 of file dir-vine.c.
References chdir(), CHECK, close(), create(), file_name, mkdir(), msg(), name, open(), quiet, readdir(), READDIR_MAX_LEN, remove(), snprintf(), strcmp(), strlen(), and write().