PKUOS - Pintos: src/lib/user/entry.c File Reference
entry.c File Reference
#include <syscall.h>
Functions
int main (int, char *[])
void _start (int argc, char *argv[])
Function Documentation
_start()
void _start (int argc, char * argv[])
Definition at line 7 of file entry.c.
References exit(), and main().
Referenced by paging_init().
main()
int main (int , char * [])
Referenced by _start().