PKUOS - Pintos: src/tests/userprog/exec-bound.c File Reference
exec-bound.c File Reference
#include <syscall.h>
#include "tests/userprog/boundary.h"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Exec a child with an exec string that spans a page boundary.
Function Documentation
test_main()
void test_main (void)
Exec a child with an exec string that spans a page boundary.
tests/main.h
Definition at line 9 of file exec-bound.c.
References copy_string_across_boundary(), exec(), and wait().