PKUOS - Pintos: src/devices/ide.h File Reference
ide.h File Reference
Functions
void ide_init (void)
devices/ide.h
Function Documentation
ide_init()
void ide_init (void)
devices/ide.h
devices/ide.h
Definition at line 102 of file ide.c.
References ata_disk::channel, CHANNEL_CNT, channels, check_device_type(), channel::completion_wait, ata_disk::dev_no, channel::devices, channel::expecting_interrupt, identify_ata_device(), interrupt_handler(), intr_register_ext(), channel::irq, ata_disk::is_ata, channel::lock, lock_init(), ata_disk::name, channel::name, NOT_REACHED, channel::reg_base, reset_channel(), sema_init(), and snprintf().
Referenced by pintos_init().