PKUOS - Pintos: src/devices/input.c File Reference
input.c File Reference
#include "devices/input.h"
#include <debug.h>
#include "devices/intq.h"
#include "devices/serial.h"
Functions
void input_init (void)
Initializes the input buffer.
void input_putc (uint8_t key)
Adds a key to the input buffer.
uint8_t input_getc (void)
Retrieves a key from the input buffer.
bool input_full (void)
Returns true if the input buffer is full, false otherwise.
Variables
static struct intq buffer
Stores keys from the keyboard and serial port.
Function Documentation
input_full()
bool input_full (void)
Returns true if the input buffer is full, false otherwise.
devices/input.h
Interrupts must be off.
Definition at line 48 of file input.c.
References ASSERT, buffer, intq_full(), intr_get_level(), and INTR_OFF.
Referenced by keyboard_interrupt(), serial_interrupt(), and write_ier().
input_getc()
uint8_t input_getc (void)
Retrieves a key from the input buffer.
If the buffer is empty, waits for a key to be pressed.
Definition at line 31 of file input.c.
References buffer, intq_getc(), intr_disable(), intr_set_level(), and serial_notify().
input_init()
void input_init (void)
Initializes the input buffer.
Definition at line 11 of file input.c.
References buffer, and intq_init().
Referenced by pintos_init().
input_putc()
void input_putc (uint8_t key)
Adds a key to the input buffer.
Interrupts must be off and the buffer must not be full.
Definition at line 19 of file input.c.
References ASSERT, buffer, intq_full(), intq_putc(), intr_get_level(), INTR_OFF, and serial_notify().
Referenced by keyboard_interrupt(), and serial_interrupt().
Variable Documentation
buffer
struct intq buffer static
Stores keys from the keyboard and serial port.
Definition at line 7 of file input.c.
Referenced by block_read(), block_write(), do_write(), file_read(), file_read_at(), file_write(), file_write_at(), fsutil_append(), fsutil_cat(), ide_read(), ide_write(), inode_read_at(), inode_write_at(), input_full(), input_getc(), input_init(), input_putc(), main(), partition_read(), partition_write(), putbuf(), read(), snprintf(), test_main(), try_write(), vsnprintf(), and write().