PKUOS - Pintos: src/threads/io.h File Reference
io.h File Reference
#include <stddef.h>
#include <stdint.h>
Functions
static uint8_t inb (uint16_t port)
Reads and returns a byte from PORT.
static void insb (uint16_t port, void *addr, size_t cnt)
Reads CNT bytes from PORT, one after another, and stores them into the buffer starting at ADDR.
static uint16_t inw (uint16_t port)
Reads and returns 16 bits from PORT.
static void insw (uint16_t port, void *addr, size_t cnt)
Reads CNT 16-bit (halfword) units from PORT, one after another, and stores them into the buffer starting at ADDR.
static uint32_t inl (uint16_t port)
Reads and returns 32 bits from PORT.
static void insl (uint16_t port, void *addr, size_t cnt)
Reads CNT 32-bit (word) units from PORT, one after another, and stores them into the buffer starting at ADDR.
static void outb (uint16_t port, uint8_t data)
Writes byte DATA to PORT.
static void outsb (uint16_t port, const void *addr, size_t cnt)
Writes to PORT each byte of data in the CNT-byte buffer starting at ADDR.
static void outw (uint16_t port, uint16_t data)
Writes the 16-bit DATA to PORT.
static void outsw (uint16_t port, const void *addr, size_t cnt)
Writes to PORT each 16-bit unit (halfword) of data in the CNT-halfword buffer starting at ADDR.
static void outl (uint16_t port, uint32_t data)
Writes the 32-bit DATA to PORT.
static void outsl (uint16_t port, const void *addr, size_t cnt)
Writes to PORT each 32-bit unit (word) of data in the CNT-word buffer starting at ADDR.
Function Documentation
inb()
static uint8_t inb (uint16_t port) inline static
Reads and returns a byte from PORT.
Definition at line 9 of file io.h.
Referenced by check_device_type(), cmos_read(), find_cursor(), interrupt_handler(), keyboard_interrupt(), putc_poll(), reset_channel(), select_device(), serial_interrupt(), shutdown_reboot(), speaker_off(), speaker_on(), wait_until_idle(), and wait_while_busy().
inl()
static uint32_t inl (uint16_t port) inline static
Reads and returns 32 bits from PORT.
Definition at line 47 of file io.h.
insb()
static void insb (uint16_t port, void * addr, size_t cnt) inline static
Reads CNT bytes from PORT, one after another, and stores them into the buffer starting at ADDR.
Definition at line 20 of file io.h.
insl()
static void insl (uint16_t port, void * addr, size_t cnt) inline static
Reads CNT 32-bit (word) units from PORT, one after another, and stores them into the buffer starting at ADDR.
Definition at line 58 of file io.h.
insw()
static void insw (uint16_t port, void * addr, size_t cnt) inline static
Reads CNT 16-bit (halfword) units from PORT, one after another, and stores them into the buffer starting at ADDR.
Definition at line 39 of file io.h.
Referenced by input_sector().
inw()
static uint16_t inw (uint16_t port) inline static
Reads and returns 16 bits from PORT.
Definition at line 28 of file io.h.
outb()
static void outb (uint16_t port, uint8_t data) inline static
Writes byte DATA to PORT.
Definition at line 66 of file io.h.
Referenced by cmos_read(), find_cursor(), init_poll(), issue_pio_command(), pic_end_of_interrupt(), pic_init(), pit_configure_channel(), putc_poll(), reset_channel(), select_device(), select_sector(), serial_interrupt(), set_serial(), shutdown_power_off(), shutdown_reboot(), speaker_off(), speaker_on(), and write_ier().
outl()
static void outl (uint16_t port, uint32_t data) inline static
Writes the 32-bit DATA to PORT.
Definition at line 100 of file io.h.
outsb()
static void outsb (uint16_t port, const void * addr, size_t cnt) inline static
Writes to PORT each byte of data in the CNT-byte buffer starting at ADDR.
Definition at line 75 of file io.h.
outsl()
static void outsl (uint16_t port, const void * addr, size_t cnt) inline static
Writes to PORT each 32-bit unit (word) of data in the CNT-word buffer starting at ADDR.
threads/io.h
Definition at line 109 of file io.h.
outsw()
static void outsw (uint16_t port, const void * addr, size_t cnt) inline static
Writes to PORT each 16-bit unit (halfword) of data in the CNT-halfword buffer starting at ADDR.
Definition at line 92 of file io.h.
Referenced by output_sector().
outw()
static void outw (uint16_t port, uint16_t data) inline static
Writes the 16-bit DATA to PORT.
Definition at line 83 of file io.h.
Referenced by move_cursor(), and shutdown_power_off().