PKUOS - Pintos: src/devices/kbd.h File Reference
kbd.h File Reference
#include <stdint.h>
Functions
void kbd_init (void)
Initializes the keyboard.
void kbd_print_stats (void)
devices/kbd.h
Function Documentation
kbd_init()
void kbd_init (void)
Initializes the keyboard.
Definition at line 31 of file kbd.c.
References intr_register_ext(), and keyboard_interrupt.
Referenced by pintos_init().
kbd_print_stats()
void kbd_print_stats (void)
devices/kbd.h
devices/kbd.h
Definition at line 38 of file kbd.c.
References key_cnt, and printf().
Referenced by print_stats().