PKUOS - Pintos: src/examples/lineup.c File Reference
lineup.c File Reference
#include <ctype.h>
#include <stdio.h>
#include <syscall.h>
Functions
int main (int argc, char *argv[])
lineup.c
Function Documentation
main()
int main (int argc , char * argv[])
lineup.c
Converts a file to uppercase in-place.
Incidentally, another way to do this while avoiding the seeks would be to open the input file, then remove() it and reopen it under another handle. Because of Unix deletion semantics this works fine.
Definition at line 15 of file lineup.c.
References buf, close(), exit(), EXIT_SUCCESS, open(), printf(), read(), seek(), tell(), toupper(), and write().