PKUOS - Pintos: src/tests/main.c File Reference
main.c File Reference
#include <random.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
int main (int argc UNUSED, char *argv[])
Function Documentation
main()
int main (int argc UNUSED, char * argv[])
Definition at line 6 of file main.c.
References msg(), random_init(), test_main(), and test_name.