PKUOS - Pintos: src/tests/filesys/extended/mk-tree.c File Reference
mk-tree.c File Reference
#include <stdio.h>
#include <syscall.h>
#include "tests/filesys/extended/mk-tree.h"
#include "tests/lib.h"
Functions
static void do_mkdir (const char *format,...) PRINTF_FORMAT(1
Library function for creating a tree of directories.
static void static void do_touch (const char *format,...) PRINTF_FORMAT(1
static void static void void make_tree (int at, int bt, int ct, int dt)
tests/filesys/extended/mk-tree.h
Function Documentation
do_mkdir()
static void do_mkdir (const char * format, ...) static
Library function for creating a tree of directories.
Definition at line 44 of file mk-tree.c.
References CHECK, mkdir(), va_end, va_start, and vsnprintf().
Referenced by make_tree().
do_touch()
static void do_touch (const char * format, ...) static
Definition at line 57 of file mk-tree.c.
References CHECK, create(), va_end, va_start, and vsnprintf().
Referenced by make_tree().
make_tree()
static void static void void make_tree (int at, int bt, int ct, int dt)
tests/filesys/extended/mk-tree.h
Definition at line 12 of file mk-tree.c.
References CHECK, close(), do_mkdir(), do_touch(), msg(), open(), quiet, and snprintf().
Referenced by test_main().