PKUOS - Pintos: src/tests/vm/mmap-clean.c File Reference
mmap-clean.c File Reference
#include <string.h>
#include <syscall.h>
#include "tests/vm/sample.inc"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Verifies that mmap'd regions are only written back on munmap if the data was actually modified in memory.
Function Documentation
test_main()
void test_main (void)
Verifies that mmap'd regions are only written back on munmap if the data was actually modified in memory.
tests/main.h
Definition at line 11 of file mmap-clean.c.
References buffer, CHECK, fail(), MAP_FAILED, memcmp(), mmap(), msg(), munmap(), open(), read(), seek(), strlen(), and write().