PKUOS - Pintos: src/tests/vm/mmap-exit.c File Reference
mmap-exit.c File Reference
#include <syscall.h>
#include "tests/vm/sample.inc"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Executes child-mm-wrt and verifies that the writes that should have occurred really did.
Function Documentation
test_main()
void test_main (void)
Executes child-mm-wrt and verifies that the writes that should have occurred really did.
tests/main.h
Definition at line 10 of file mmap-exit.c.
References CHECK, check_file(), exec(), quiet, and wait().