PKUOS - Pintos: src/tests/userprog/multi-recurse.c File Reference
multi-recurse.c File Reference
#include <debug.h>
#include <stdlib.h>
#include <stdio.h>
#include <syscall.h>
#include "tests/lib.h"
Functions
int main (int argc UNUSED, char *argv[])
Variables
const char * test_name = "multi-recurse"
Executes itself recursively to the depth indicated by the first command-line argument.
Function Documentation
main()
int main (int argc UNUSED, char * argv[])
Definition at line 13 of file multi-recurse.c.
References atoi(), CHECK, exec(), fail(), msg(), snprintf(), and wait().
Variable Documentation
test_name
const char* test_name = "multi-recurse"
Executes itself recursively to the depth indicated by the first command-line argument.
Child process for syn-read test.
Definition at line 10 of file multi-recurse.c.