PKUOS - Pintos: src/tests/vm/parallel-merge.h File Reference
parallel-merge.h File Reference
Functions
void parallel_merge (const char *child_name, int exit_status)
tests/vm/parallel-merge.h
Function Documentation
parallel_merge()
void parallel_merge (const char * child_name, int exit_status)
tests/vm/parallel-merge.h
Definition at line 143 of file parallel-merge.c.
References init(), merge(), sort_chunks(), and verify().
Referenced by test_main().