PKUOS - Pintos: src/devices/partition.h File Reference
partition.h File Reference
Functions
void partition_scan (struct block *)
devices/partition.h
Function Documentation
partition_scan()
void partition_scan (struct block * block)
devices/partition.h
devices/partition.h
Definition at line 28 of file partition.c.
References block_name(), printf(), and read_partition_table().
Referenced by identify_ata_device().