PKUOS - Pintos: src/tests/vm/pt-big-stk-obj.c File Reference
pt-big-stk-obj.c File Reference
#include <string.h>
#include "tests/arc4.h"
#include "tests/cksum.h"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Allocates and writes to a 64 kB object on the stack.
Function Documentation
test_main()
void test_main (void)
Allocates and writes to a 64 kB object on the stack.
tests/main.h
This must succeed.
Definition at line 11 of file pt-big-stk-obj.c.
References arc4_crypt(), arc4_init(), cksum(), memset(), and msg().