PKUOS - Pintos: src/tests/vm/pt-grow-stk-sc.c File Reference
pt-grow-stk-sc.c File Reference
#include <string.h>
#include <syscall.h>
#include "tests/vm/sample.inc"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
This test checks that the stack is properly extended even if the first access to a stack location occurs inside a system call.
Function Documentation
test_main()
void test_main (void)
This test checks that the stack is properly extended even if the first access to a stack location occurs inside a system call.
tests/main.h
From Godmar Back.
< Save a copy of the stack pointer.
< Move stack pointer to bottom of page.
< Push 32 bytes on stack at once.
< Restore copied stack pointer.
< Tell GCC we destroyed eax.
Definition at line 14 of file pt-grow-stk-sc.c.
References buf2, CHECK, close(), create(), memcmp(), open(), read(), strlen(), and write().