PKUOS - Pintos: src/tests/userprog/read-bad-ptr.c File Reference
read-bad-ptr.c File Reference
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Passes an invalid pointer to the read system call.
Function Documentation
test_main()
void test_main (void)
Passes an invalid pointer to the read system call.
tests/main.h
The process must be terminated with -1 exit code.
Definition at line 9 of file read-bad-ptr.c.
References CHECK, fail(), open(), and read().