PKUOS - Pintos: src/tests/userprog/read-boundary.c File Reference
read-boundary.c File Reference
#include <string.h>
#include <syscall.h>
#include "tests/userprog/boundary.h"
#include "tests/userprog/sample.inc"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Reads data spanning two pages in virtual address space, which must succeed.
Function Documentation
test_main()
void test_main (void)
Reads data spanning two pages in virtual address space, which must succeed.
tests/main.h
Definition at line 12 of file read-boundary.c.
References buffer, byte_cnt(), CHECK, fail(), get_boundary_area(), msg(), open(), read(), and strcmp().