PKUOS - Pintos: src/examples/recursor.c File Reference
recursor.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <syscall.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc , char * argv[])
Definition at line 6 of file recursor.c.
References atoi(), buffer, exec(), exit(), printf(), snprintf(), and wait().