PKUOS - Pintos: src/lib/stdlib.h File Reference
stdlib.h File Reference
#include <stddef.h>
Functions
int atoi (const char *)
Standard functions.
void qsort (void *array, size_t cnt, size_t size, int(*compare)(const void *, const void *))
Sorts ARRAY, which contains CNT elements of SIZE bytes each, using COMPARE.
void * bsearch (const void *key, const void *array, size_t cnt, size_t size, int(*compare)(const void *, const void *))
Searches ARRAY, which contains CNT elements of SIZE bytes each, for the given KEY.
void sort (void *array, size_t cnt, size_t size, int(*compare)(const void *, const void *, void *aux), void *aux)
Nonstandard functions.
void * binary_search (const void *key, const void *array, size_t cnt, size_t size, int(*compare)(const void *, const void *, void *aux), void *aux)
lib/stdlib.h
Function Documentation
atoi()
int atoi (const char * s)
Standard functions.
Standard functions.
Definition at line 10 of file stdlib.c.
References ASSERT, isdigit(), isspace(), NULL, and s.
Referenced by expand(), main(), and parse_options().
binary_search()
void * binary_search (const void * key, const void * array, size_t cnt, size_t size, int(*)(const void *, const void *, void *aux) compare, void * aux)
lib/stdlib.h
lib/stdlib.h
Returns a match is found, otherwise a null pointer. If there are multiple matches, returns an arbitrary one of them.
ARRAY must be sorted in order according to COMPARE.
Uses COMPARE to compare elements, passing AUX as auxiliary data. When COMPARE is passed a pair of elements A and B, respectively, it must return a strcmp()-type result, i.e. less than zero if A < B, zero if A == B, greater than zero if A > B.
Definition at line 185 of file stdlib.c.
References NULL.
Referenced by bsearch().
bsearch()
void * bsearch (const void * key, const void * array, size_t cnt, size_t size, int(*)(const void *, const void *) compare)
Searches ARRAY, which contains CNT elements of SIZE bytes each, for the given KEY.
Returns a match is found, otherwise a null pointer. If there are multiple matches, returns an arbitrary one of them.
ARRAY must be sorted in order according to COMPARE.
Uses COMPARE to compare elements. When COMPARE is passed a pair of elements A and B, respectively, it must return a strcmp()-type result, i.e. less than zero if A < B, zero if A == B, greater than zero if A > B.
Definition at line 166 of file stdlib.c.
References binary_search(), and compare_thunk().
Referenced by verify_bsearch().
qsort()
void qsort (void * array, size_t cnt, size_t size, int(*)(const void *, const void *) compare)
Sorts ARRAY, which contains CNT elements of SIZE bytes each, using COMPARE.
When COMPARE is passed a pair of elements A and B, respectively, it must return a strcmp()-type result, i.e. less than zero if A < B, zero if A == B, greater than zero if A > B. Runs in O(n lg n) time and O(1) space in CNT.
Definition at line 58 of file stdlib.c.
References compare_thunk(), and sort().
Referenced by test().
sort()
void sort (void * array, size_t cnt, size_t size, int(*)(const void *, const void *, void *aux) compare, void * aux)
Nonstandard functions.
Nonstandard functions.
When COMPARE is passed a pair of elements A and B, respectively, it must return a strcmp()-type result, i.e. less than zero if A < B, zero if A == B, greater than zero if A > B. Runs in O(n lg n) time and O(1) space in CNT.
Definition at line 132 of file stdlib.c.
References ASSERT, do_swap(), heapify(), and NULL.
Referenced by qsort().