PKUOS - Pintos: src/tests/filesys/base/syn-remove.c File Reference
syn-remove.c File Reference
#include <random.h>
#include <string.h>
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
tests/main.h
Variables
char buf1 [1234]
Verifies that a deleted file may still be written to and read from.
char buf2 [1234]
Function Documentation
test_main()
void test_main (void)
tests/main.h
Definition at line 14 of file syn-remove.c.
References buf1, buf2, CHECK, close(), compare_bytes(), create(), file_name, msg(), open(), random_bytes(), read(), remove(), seek(), and write().
Variable Documentation
buf1
char buf1[1234]
Verifies that a deleted file may still be written to and read from.
Definition at line 10 of file syn-remove.c.
Referenced by test_main().
buf2
char buf2[1234]
Definition at line 11 of file syn-remove.c.
Referenced by test_main().