PKUOS - Pintos: src/tests/filesys/base/syn-read.c File Reference
syn-read.c File Reference
#include <random.h>
#include <stdio.h>
#include <syscall.h>
#include "tests/lib.h"
#include "tests/main.h"
#include "tests/filesys/base/syn-read.h"
Macros
#define CHILD_CNT 10
Functions
void test_main (void)
tests/main.h
Variables
static char buf [BUF_SIZE]
Spawns 10 child processes, all of which read from the same file and make sure that the contents are what they should be.
Macro Definition Documentation
CHILD_CNT
#define CHILD_CNT 10
Definition at line 14 of file syn-read.c.
Function Documentation
test_main()
void test_main (void)
tests/main.h
Definition at line 17 of file syn-read.c.
References buf, CHECK, CHILD_CNT, close(), create(), exec_children(), file_name, msg(), open(), random_bytes(), wait_children(), and write().
Referenced by main().
Variable Documentation
buf
char buf[BUF_SIZE] static
Spawns 10 child processes, all of which read from the same file and make sure that the contents are what they should be.
Definition at line 12 of file syn-read.c.
Referenced by test_main().