PKUOS - Pintos: src/tests/filesys/base/syn-write.c File Reference
syn-write.c File Reference
#include <random.h>
#include <stdio.h>
#include <string.h>
#include <syscall.h>
#include "tests/filesys/base/syn-write.h"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
tests/main.h
Variables
char buf1 [BUF_SIZE]
Spawns several child processes to write out different parts of the contents of a file and waits for them to finish.
char buf2 [BUF_SIZE]
Function Documentation
test_main()
void test_main (void)
tests/main.h
Definition at line 17 of file syn-write.c.
References buf1, buf2, CHECK, CHILD_CNT, compare_bytes(), create(), exec_children(), file_name, open(), random_bytes(), read(), and wait_children().
Variable Documentation
buf1
char buf1[BUF_SIZE]
Spawns several child processes to write out different parts of the contents of a file and waits for them to finish.
Then reads back the file and verifies its contents.
Definition at line 13 of file syn-write.c.
Referenced by test_main().
buf2
char buf2[BUF_SIZE]
Definition at line 14 of file syn-write.c.
Referenced by test_main().