PKUOS - Pintos: src/userprog/tss.h File Reference
tss.h File Reference
#include <stdint.h>
Functions
void tss_init (void)
Initializes the kernel TSS.
struct tss * tss_get (void)
Returns the kernel TSS.
void tss_update (void)
userprog/tss.h
Function Documentation
tss_get()
struct tss * tss_get (void)
Returns the kernel TSS.
Definition at line 93 of file tss.c.
References ASSERT, NULL, and tss.
Referenced by gdt_init().
tss_init()
void tss_init (void)
Initializes the kernel TSS.
Definition at line 80 of file tss.c.
References tss::bitmap, PAL_ASSERT, PAL_ZERO, palloc_get_page(), SEL_KDSEG, tss::ss0, and tss_update().
Referenced by pintos_init().
tss_update()
void tss_update (void)
userprog/tss.h
userprog/tss.h
Definition at line 102 of file tss.c.
References ASSERT, tss::esp0, NULL, PGSIZE, and thread_current().
Referenced by process_activate(), and tss_init().