PKUOS - Pintos: src/lib/user/debug.c File Reference
debug.c File Reference
#include <debug.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <syscall.h>
Functions
void debug_panic (const char *file, int line, const char *function, const char *message,...)
Aborts the user program, printing the source file name, line number, and function name, plus a user-specific message.
Function Documentation
debug_panic()
void debug_panic (const char * file, int line, const char * function, const char * message, ...)
Aborts the user program, printing the source file name, line number, and function name, plus a user-specific message.
Definition at line 10 of file debug.c.
References debug_backtrace(), exit(), printf(), va_end, va_start, and vprintf().