PKUOS - Pintos: src/userprog/syscall.c File Reference
syscall.c File Reference
#include "userprog/syscall.h"
#include <stdio.h>
#include <syscall-nr.h>
#include "threads/interrupt.h"
#include "threads/thread.h"
Functions
static void syscall_handler (struct intr_frame *)
void syscall_init (void)
userprog/syscall.h
static void syscall_handler (struct intr_frame *f UNUSED)
Function Documentation
syscall_handler() [1/2]
static void syscall_handler (struct intr_frame *) static
Referenced by syscall_init().
syscall_handler() [2/2]
static void syscall_handler (struct intr_frame *f UNUSED) static
Definition at line 16 of file syscall.c.
References printf(), and thread_exit().
syscall_init()
void syscall_init (void)
userprog/syscall.h
Definition at line 10 of file syscall.c.
References INTR_ON, intr_register_int(), and syscall_handler().
Referenced by pintos_init().