PKUOS - Pintos: src/devices/vga.h File Reference
vga.h File Reference
Functions
void vga_putc (int)
devices/vga.h
Function Documentation
vga_putc()
void vga_putc (int c)
devices/vga.h
devices/vga.h
Definition at line 52 of file vga.c.
References cls(), COL_CNT, cx, cy, fb, GRAY_ON_BLACK, init(), intr_disable(), intr_set_level(), move_cursor(), newline(), ROUND_UP, and speaker_beep().
Referenced by putchar_have_lock().