PKUOS - Pintos: src/tests/userprog/write-boundary.c File Reference
write-boundary.c File Reference
#include <string.h>
#include <syscall.h>
#include "tests/userprog/boundary.h"
#include "tests/userprog/sample.inc"
#include "tests/lib.h"
#include "tests/main.h"
Functions
void test_main (void)
Writes data spanning two pages in virtual address space, which must succeed.
Function Documentation
test_main()
void test_main (void)
Writes data spanning two pages in virtual address space, which must succeed.
tests/main.h
Definition at line 12 of file write-boundary.c.
References byte_cnt(), CHECK, copy_string_across_boundary(), fail(), open(), and write().